site_name: Mack Lab Knowledge Base

plugins:
  - search
  - awesome-pages

theme: 
  logo: macklablogo.png
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    #- navigation.indexes
    - navigation.top
    - toc.follow
    - content.code.copy

markdown_extensions:
  - attr_list
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: Copyright &copy; 2024 University of Toronto, Department of Psychology, Mack Lab 
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://www.github.com/macklab
    #- icon: fontawesome/solid/map-location-dot
    #  link: https://goo.gl/maps/S5vs23BHGHeHxcYY6
#  version:
#    provider: mike
